### ISSUE TITLE
Mongoid5 support

### ISSUE THREAD

**Issue by mensfeld** [mongoid-rspec/mongoid-rspec#151]
Hey, there's already a Mongoid5 beta - are you guys planning to support it?

If so, could I ask about a timeframe?

**Comment by rodrigopinto** [comment]
@mensfeld currently this gem is unmaintained, if you send a pull request we could merge it. Thanks

**Comment by mensfeld** [comment]
I work with @90yukke and hopefully he will do that tomorrow @ work ;)

**Comment by rodrigopinto** [comment]
@mensfeld perfect!!! @90yukke Thank you very much again. :+1: :smile:

**Comment by nofxx** [comment]
Might be closed...  https://github.com/mongoid-rspec/mongoid-rspec/pull/149

But somehow 2.2.0 is requiring mongoid ~> 4.0.0 here!
Crazy, was working yeasterday! Grrrrr

**Comment by nofxx** [comment]
Ops! We got a `--pre` now! Missed the readme hehe. TY!

**Comment by vitalis** [comment]
Is it possible to release version with Mongoid 5.0.0 support ? :)

**Comment by 90yukke** [comment]
@vitalis i'm waiting for a @rodrigopinto, hope he will publish it to rubygems today.

**Comment by vitalis** [comment]
@90yukke , @rodrigopinto thanks !!
