### ISSUE TITLE
undefined method `validate_uniqueness_of'

### ISSUE THREAD

**Issue by spurnaye** [mongoid-rspec/mongoid-rspec#160]
Hello,
 I am getting error mentioned above:
```
     Failure/Error: it { is_expected.to validate_uniqueness_of(:name) }
     NoMethodError:
       undefined method `validate_uniqueness_of' for #<RSpec::ExampleGroups::Word:0x007fe6c59525a0>
```

mongoid-5.0.0
mongoid-rspec-3.0.0

**Comment by 90yukke** [comment]
Hi @spurnaye. Could you show your `spec_helper.rb` and, possibly, `rails_helper.rb`

**Comment by spurnaye** [comment]
Hey @90yukke, I think there was some configuration missing from my side. Everything is good now.

I had to include 
```
require 'mongoid-rspec'
  config.include Mongoid::Matchers, type: :model

```
