### ISSUE TITLE
Deprecate and remove useless matchers

### ISSUE THREAD

**Issue by 90yukke** [mongoid-rspec/mongoid-rspec#166]
Next matchers should be deprecated and removed in upcoming versions of mongoid-rspec: 
1. `be_paranoid_document`, because of removal `Mongoid::MultiParameterAttributes` since mongoid version 4.0
2. `be_multiparameted_document` because of removal `Mongoid::Paranoia` since mongoid version 4.0
3. `be_versioned_document` because of removal `Mongoid::Versioning` out of mongoid
4. `have_instance_method` since it has nothing related to features of mongoid

**Comment by rodrigopinto** [comment]
It's makes sense. Thanks. :+1:
