### ISSUE TITLE
Mongoid6- rails5 compatibility

### ISSUE THREAD

**Issue by shipdcare** [mongoid-rspec/mongoid-rspec#171]
Getting an error:  
mongoid-rspec (= 3.0.0) was resolved to 3.0.0, which depends on
      mongoid (~> 5.0)

**Comment by phinfonet** [comment]
@shipdcare feel free to use my fork of gem. =D https://github.com/phinfonet/mongoid-rspec

**Comment by rodrigopinto** [comment]
Closing issue, related to https://github.com/mongoid-rspec/mongoid-rspec/issues/169
