### ISSUE TITLE
validates_numericality_of only_integer not working

### ISSUE THREAD

**Issue by obahareth** [mongoid-rspec/mongoid-rspec#188]
I'm trying to do this:

```ruby
# Model
validates :login_attempts_in_last_hour,
            numericality: { greater_than_or_equal_to: 0 }

# Spec
it do
        is_expected.to validate_numericality_of(:login_attempts_in_last_hour)
                         .to_allow(greater_than_or_equal_to: 0,
                                   only_integer: true)
end
```

and when I run rspec it doesn't throw any errors, even though my model hasn't validated that the property only allows integers. It only ever throws an error if you forcefully set `only_integer: false` in the model.

**Comment by 90yukke** [comment]
@obahareth What version of mongoid-rspec are you using?

**Comment by obahareth** [comment]
Whichever it is you get when you do:

`gem 'mongoid-rspec', github: 'mongoid-rspec/mongoid-rspec'` 

According to my GemFile.lock, it's `mongoid-rspec (4.0.0.pre.alpha1)`.
